# Generated by Django 3.1.7 on 2021-03-09 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globalEventsAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WildfireEvent',
            new_name='MODISEventRecord',
        ),
    ]
