# Generated by Django 3.1.6 on 2021-02-05 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=150, primary_key=True, serialize=False, verbose_name='Username')),
                ('password', models.CharField(max_length=150, verbose_name='User Password')),
                ('country', models.CharField(max_length=56, null=True, verbose_name='Country')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date Joined')),
                ('last_login', models.DateTimeField(auto_now_add=True, verbose_name='Last Login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=150, unique=True, verbose_name='Email Address')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
