# Generated by Django 3.1.7 on 2021-03-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WildfireEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('bright_ti4', models.FloatField()),
                ('scan', models.FloatField()),
                ('track', models.FloatField()),
                ('acq_date', models.CharField(max_length=255)),
                ('acq_time', models.CharField(max_length=255)),
                ('satellite', models.CharField(max_length=100)),
                ('confidence', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=100)),
                ('bright_ti5', models.FloatField()),
                ('frp', models.FloatField()),
                ('daynight', models.CharField(max_length=1)),
            ],
        ),
    ]
