# Generated by Django 3.2.5 on 2021-08-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_resolution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='confidence',
            field=models.IntegerField(),
        ),
    ]
