# Generated by Django 3.2.5 on 2021-08-08 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_confidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='confidence',
            field=models.CharField(max_length=50),
        ),
    ]
