# Generated by Django 3.2.5 on 2021-08-24 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_confidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_user_made',
            field=models.CharField(default='n', max_length=1),
            preserve_default=False,
        ),
    ]
