# Generated by Django 3.2.5 on 2021-08-31 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_is_user_made'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='acq_date',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='acq_time',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='bright_ti4',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='bright_ti5',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='daynight',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='frp',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='resolution',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='satellite',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='scan',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='track',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='version',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
